/**
 * Departamentos y municipios de Colombia
 * Con metadata de cobertura y costos de envío
 * 
 * Cobertura:
 * - TIER_1: Ciudades principales (Bogotá, Medellín, Cali, Barranquilla, etc.)
 * - TIER_2: Ciudades intermedias (capitales de departamento + ciudades grandes)
 * - TIER_3: Municipios pequeños (con punto de recogida)
 * - TIER_4: Zonas rurales (envío a ciudad cercana con punto)
 */

export type ShippingTier = 1 | 2 | 3 | 4;

export interface Municipio {
  nombre: string;
  tier: ShippingTier;
}

export interface Departamento {
  codigo: string;
  nombre: string;
  municipios: Municipio[];
}

// Departamentos principales con TIER asignado
const TIER_1 = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Manizales', 'Santa Marta', 'Cúcuta', 'Ibagué', 'Villavicencio', 'Pasto', 'Montería', 'Armenia', 'Neiva', 'Valledupar', 'Sincelejo', 'Popayán', 'Tunja'];

export const DEPARTAMENTOS_COLOMBIA: Departamento[] = [
  {
    codigo: '05',
    nombre: 'Antioquia',
    municipios: [
      { nombre: 'Medellín', tier: 1 },
      { nombre: 'Bello', tier: 1 },
      { nombre: 'Envigado', tier: 1 },
      { nombre: 'Itagüí', tier: 1 },
      { nombre: 'Rionegro', tier: 1 },
      { nombre: 'Sabaneta', tier: 1 },
      { nombre: 'La Estrella', tier: 1 },
      { nombre: 'Copacabana', tier: 1 },
      { nombre: 'Girardota', tier: 1 },
      { nombre: 'Barbosa', tier: 1 },
      { nombre: 'Apartadó', tier: 2 },
      { nombre: 'Turbo', tier: 2 },
      { nombre: 'Caucasia', tier: 2 },
      { nombre: 'Rionegro', tier: 2 },
      { nombre: 'La Ceja', tier: 2 },
      { nombre: 'Marinilla', tier: 2 },
      { nombre: 'El Carmen de Viboral', tier: 2 },
      { nombre: 'Guarne', tier: 2 },
      { nombre: 'Santa Fe de Antioquia', tier: 2 },
      { nombre: 'Andes', tier: 3 },
      { nombre: 'Sonsón', tier: 3 },
      { nombre: 'Puerto Berrío', tier: 3 },
      { nombre: 'Yarumal', tier: 3 },
      { nombre: 'Zaragoza', tier: 3 },
      { nombre: 'Segovia', tier: 3 },
      { nombre: 'Remedios', tier: 3 },
      { nombre: 'Amalfi', tier: 3 },
      { nombre: 'Yolombó', tier: 3 },
      { nombre: 'Santo Domingo', tier: 3 },
      { nombre: 'Cisneros', tier: 3 },
      { nombre: 'Yondó', tier: 3 },
      { nombre: 'Puerto Triunfo', tier: 3 },
      { nombre: 'San Luis', tier: 3 },
      { nombre: 'San Carlos', tier: 3 },
      { nombre: 'San Rafael', tier: 3 },
      { nombre: 'Alejandría', tier: 3 },
      { nombre: 'Concepción', tier: 3 },
      { nombre: 'San Vicente Ferrer', tier: 3 },
      { nombre: 'Barbosa', tier: 3 },
      { nombre: 'Donmatías', tier: 3 },
      { nombre: 'Entrerríos', tier: 3 },
      { nombre: 'Gómez Plata', tier: 4 },
      { nombre: 'Angostura', tier: 4 },
      { nombre: 'Belmira', tier: 4 },
      { nombre: 'San Pedro de los Milagros', tier: 4 },
      { nombre: 'Santa Rosa de Osos', tier: 4 },
      { nombre: 'Yalí', tier: 4 },
      { nombre: 'Vegachí', tier: 4 },
      { nombre: 'Amagá', tier: 3 },
      { nombre: 'Angelópolis', tier: 4 },
      { nombre: 'Titiribí', tier: 4 },
      { nombre: 'Venecia', tier: 4 },
      { nombre: 'Fredonia', tier: 4 },
      { nombre: 'Santa Bárbara', tier: 4 },
      { nombre: 'Abejorral', tier: 4 },
      { nombre: 'Sonsón', tier: 3 },
      { nombre: 'Nariño', tier: 4 },
      { nombre: 'Argelia', tier: 4 },
    ],
  },
  {
    codigo: '08',
    nombre: 'Atlántico',
    municipios: [
      { nombre: 'Barranquilla', tier: 1 },
      { nombre: 'Soledad', tier: 1 },
      { nombre: 'Malambo', tier: 1 },
      { nombre: 'Puerto Colombia', tier: 2 },
      { nombre: 'Galapa', tier: 2 },
      { nombre: 'Sabanagrande', tier: 2 },
      { nombre: 'Sabanalarga', tier: 2 },
      { nombre: 'Baranoa', tier: 2 },
      { nombre: 'Palmar de Varela', tier: 3 },
      { nombre: 'Santo Tomás', tier: 3 },
      { nombre: 'Polonuevo', tier: 3 },
      { nombre: 'Ponedera', tier: 3 },
      { nombre: 'Campo de la Cruz', tier: 3 },
      { nombre: 'Candelaria', tier: 3 },
      { nombre: 'Manatí', tier: 4 },
      { nombre: 'Repelón', tier: 4 },
      { nombre: 'Luruaco', tier: 4 },
      { nombre: 'Santa Lucía', tier: 4 },
      { nombre: 'Suan', tier: 4 },
      { nombre: 'Juan de Acosta', tier: 4 },
      { nombre: 'Tubará', tier: 4 },
      { nombre: 'Usiacurí', tier: 4 },
      { nombre: 'Piojó', tier: 4 },
    ],
  },
  {
    codigo: '11',
    nombre: 'Bogotá D.C.',
    municipios: [
      { nombre: 'Bogotá', tier: 1 },
      { nombre: 'Usaquén', tier: 1 },
      { nombre: 'Chapinero', tier: 1 },
      { nombre: 'Santa Fe', tier: 1 },
      { nombre: 'San Cristóbal', tier: 1 },
      { nombre: 'Usme', tier: 2 },
      { nombre: 'Tunjuelito', tier: 1 },
      { nombre: 'Bosa', tier: 1 },
      { nombre: 'Kennedy', tier: 1 },
      { nombre: 'Fontibón', tier: 1 },
      { nombre: 'Engativá', tier: 1 },
      { nombre: 'Suba', tier: 1 },
      { nombre: 'Barrios Unidos', tier: 1 },
      { nombre: 'Teusaquillo', tier: 1 },
      { nombre: 'Los Mártires', tier: 1 },
      { nombre: 'Antonio Nariño', tier: 1 },
      { nombre: 'Puente Aranda', tier: 1 },
      { nombre: 'La Candelaria', tier: 1 },
      { nombre: 'Rafael Uribe Uribe', tier: 1 },
      { nombre: 'Ciudad Bolívar', tier: 2 },
      { nombre: 'Sumapaz', tier: 4 },
    ],
  },
  {
    codigo: '13',
    nombre: 'Bolívar',
    municipios: [
      { nombre: 'Cartagena', tier: 1 },
      { nombre: 'Magangué', tier: 2 },
      { nombre: 'Turbaco', tier: 2 },
      { nombre: 'Arjona', tier: 2 },
      { nombre: 'El Carmen de Bolívar', tier: 2 },
      { nombre: 'Santa Rosa del Sur', tier: 3 },
      { nombre: 'Mompox', tier: 3 },
      { nombre: 'San Juan Nepomuceno', tier: 3 },
      { nombre: 'María La Baja', tier: 3 },
      { nombre: 'San Jacinto', tier: 3 },
      { nombre: 'Calamar', tier: 3 },
      { nombre: 'Mahates', tier: 3 },
      { nombre: 'Villanueva', tier: 3 },
      { nombre: 'San Estanislao', tier: 4 },
      { nombre: 'Soplaviento', tier: 4 },
      { nombre: 'Turbana', tier: 4 },
      { nombre: 'San Pablo', tier: 4 },
      { nombre: 'Simití', tier: 4 },
      { nombre: 'Río Viejo', tier: 4 },
      { nombre: 'Morales', tier: 4 },
      { nombre: 'Zambrano', tier: 4 },
      { nombre: 'Cantagallo', tier: 4 },
    ],
  },
  {
    codigo: '15',
    nombre: 'Boyacá',
    municipios: [
      { nombre: 'Tunja', tier: 1 },
      { nombre: 'Sogamoso', tier: 2 },
      { nombre: 'Duitama', tier: 2 },
      { nombre: 'Chiquinquirá', tier: 2 },
      { nombre: 'Paipa', tier: 2 },
      { nombre: 'Puerto Boyacá', tier: 2 },
      { nombre: 'Villa de Leyva', tier: 2 },
      { nombre: 'Nobsa', tier: 3 },
      { nombre: 'Aquitania', tier: 3 },
      { nombre: 'Garagoa', tier: 3 },
      { nombre: 'Miraflores', tier: 3 },
      { nombre: 'Ramiriquí', tier: 3 },
      { nombre: 'Samacá', tier: 3 },
      { nombre: 'Tibasosa', tier: 3 },
      { nombre: 'Tuta', tier: 3 },
      { nombre: 'Ventaquemada', tier: 3 },
      { nombre: 'Moniquirá', tier: 3 },
      { nombre: 'Soatá', tier: 4 },
      { nombre: 'Belén', tier: 4 },
      { nombre: 'Boavita', tier: 4 },
      { nombre: 'Cubará', tier: 4 },
      { nombre: 'El Cocuy', tier: 4 },
      { nombre: 'Guican', tier: 4 },
      { nombre: 'Jericó', tier: 4 },
      { nombre: 'La Uvita', tier: 4 },
      { nombre: 'Sativanorte', tier: 4 },
      { nombre: 'Sativasur', tier: 4 },
      { nombre: 'Susacón', tier: 4 },
      { nombre: 'Tipacoque', tier: 4 },
    ],
  },
  {
    codigo: '17',
    nombre: 'Caldas',
    municipios: [
      { nombre: 'Manizales', tier: 1 },
      { nombre: 'La Dorada', tier: 2 },
      { nombre: 'Villamaría', tier: 2 },
      { nombre: 'Chinchiná', tier: 2 },
      { nombre: 'Riosucio', tier: 3 },
      { nombre: 'Anserma', tier: 3 },
      { nombre: 'Aguadas', tier: 3 },
      { nombre: 'Salamina', tier: 3 },
      { nombre: 'Neira', tier: 3 },
      { nombre: 'Palestina', tier: 4 },
      { nombre: 'Pensilvania', tier: 4 },
      { nombre: 'Samaná', tier: 4 },
      { nombre: 'Victoria', tier: 4 },
      { nombre: 'Marquetalia', tier: 4 },
      { nombre: 'Marulanda', tier: 4 },
    ],
  },
  {
    codigo: '18',
    nombre: 'Caquetá',
    municipios: [
      { nombre: 'Florencia', tier: 2 },
      { nombre: 'San Vicente del Caguán', tier: 3 },
      { nombre: 'Puerto Rico', tier: 3 },
      { nombre: 'El Paujil', tier: 3 },
      { nombre: 'La Montañita', tier: 4 },
      { nombre: 'Cartagena del Chairá', tier: 4 },
      { nombre: 'Belén de los Andaquíes', tier: 4 },
      { nombre: 'Morelia', tier: 4 },
      { nombre: 'Milán', tier: 4 },
      { nombre: 'Solano', tier: 4 },
      { nombre: 'Solita', tier: 4 },
      { nombre: 'Valparaíso', tier: 4 },
      { nombre: 'Albania', tier: 4 },
      { nombre: 'Curillo', tier: 4 },
      { nombre: 'San José del Fragua', tier: 4 },
    ],
  },
  {
    codigo: '19',
    nombre: 'Cauca',
    municipios: [
      { nombre: 'Popayán', tier: 1 },
      { nombre: 'Santander de Quilichao', tier: 2 },
      { nombre: 'Puerto Tejada', tier: 2 },
      { nombre: 'Patía', tier: 2 },
      { nombre: 'Miranda', tier: 3 },
      { nombre: 'Corinto', tier: 3 },
      { nombre: 'Caloto', tier: 3 },
      { nombre: 'Piendamó', tier: 3 },
      { nombre: 'Cajibío', tier: 3 },
      { nombre: 'Timbío', tier: 3 },
      { nombre: 'Rosas', tier: 3 },
      { nombre: 'Mercaderes', tier: 4 },
      { nombre: 'Bolívar', tier: 4 },
      { nombre: 'Almaguer', tier: 4 },
      { nombre: 'San Sebastián', tier: 4 },
      { nombre: 'Sucre', tier: 4 },
      { nombre: 'La Vega', tier: 4 },
      { nombre: 'Argelia', tier: 4 },
      { nombre: 'El Tambo', tier: 4 },
      { nombre: 'Guapi', tier: 4 },
      { nombre: 'Timbiquí', tier: 4 },
      { nombre: 'López de Micay', tier: 4 },
    ],
  },
  {
    codigo: '20',
    nombre: 'Cesar',
    municipios: [
      { nombre: 'Valledupar', tier: 1 },
      { nombre: 'Aguachica', tier: 2 },
      { nombre: 'Agustín Codazzi', tier: 2 },
      { nombre: 'Bosconia', tier: 2 },
      { nombre: 'La Jagua de Ibirico', tier: 3 },
      { nombre: 'Curumaní', tier: 3 },
      { nombre: 'Chiriguaná', tier: 3 },
      { nombre: 'El Copey', tier: 3 },
      { nombre: 'La Paz', tier: 3 },
      { nombre: 'San Alberto', tier: 3 },
      { nombre: 'San Martín', tier: 4 },
      { nombre: 'Río de Oro', tier: 4 },
      { nombre: 'Pueblo Bello', tier: 4 },
      { nombre: 'Manaure', tier: 4 },
      { nombre: 'Becerril', tier: 4 },
      { nombre: 'La Gloria', tier: 4 },
      { nombre: 'Pelaya', tier: 4 },
      { nombre: 'Pailitas', tier: 4 },
      { nombre: 'Tamalameque', tier: 4 },
      { nombre: 'Astrea', tier: 4 },
      { nombre: 'Chimichagua', tier: 4 },
      { nombre: 'Gamarra', tier: 4 },
      { nombre: 'González', tier: 4 },
      { nombre: 'El Paso', tier: 4 },
    ],
  },
  {
    codigo: '23',
    nombre: 'Córdoba',
    municipios: [
      { nombre: 'Montería', tier: 1 },
      { nombre: 'Cereté', tier: 2 },
      { nombre: 'Lorica', tier: 2 },
      { nombre: 'Sahagún', tier: 2 },
      { nombre: 'Planeta Rica', tier: 2 },
      { nombre: 'Montelíbano', tier: 3 },
      { nombre: 'Tierralta', tier: 3 },
      { nombre: 'Valencia', tier: 3 },
      { nombre: 'San Pelayo', tier: 3 },
      { nombre: 'Ciénaga de Oro', tier: 3 },
      { nombre: 'Chinú', tier: 3 },
      { nombre: 'Cotorra', tier: 4 },
      { nombre: 'Momil', tier: 4 },
      { nombre: 'Purísima', tier: 4 },
      { nombre: 'Moñitos', tier: 4 },
      { nombre: 'Puerto Escondido', tier: 4 },
      { nombre: 'Los Córdobas', tier: 4 },
      { nombre: 'Canalete', tier: 4 },
      { nombre: 'San Bernardo del Viento', tier: 4 },
      { nombre: 'San Antero', tier: 4 },
      { nombre: 'Buenavista', tier: 4 },
      { nombre: 'La Apartada', tier: 4 },
      { nombre: 'Ayapel', tier: 4 },
    ],
  },
  {
    codigo: '25',
    nombre: 'Cundinamarca',
    municipios: [
      { nombre: 'Soacha', tier: 1 },
      { nombre: 'Chía', tier: 1 },
      { nombre: 'Zipaquirá', tier: 1 },
      { nombre: 'Facatativá', tier: 1 },
      { nombre: 'Fusagasugá', tier: 2 },
      { nombre: 'Madrid', tier: 2 },
      { nombre: 'Mosquera', tier: 2 },
      { nombre: 'Funza', tier: 2 },
      { nombre: 'Cajicá', tier: 2 },
      { nombre: 'Tocancipá', tier: 2 },
      { nombre: 'La Calera', tier: 2 },
      { nombre: 'Sibaté', tier: 2 },
      { nombre: 'Girardot', tier: 2 },
      { nombre: 'Sopó', tier: 2 },
      { nombre: 'Cota', tier: 2 },
      { nombre: 'Tenjo', tier: 3 },
      { nombre: 'Tabio', tier: 3 },
      { nombre: 'Subachoque', tier: 3 },
      { nombre: 'El Rosal', tier: 3 },
      { nombre: 'Bojacá', tier: 3 },
      { nombre: 'Zipacón', tier: 4 },
      { nombre: 'Anolaima', tier: 4 },
      { nombre: 'La Mesa', tier: 3 },
      { nombre: 'San Antonio del Tequendama', tier: 4 },
      { nombre: 'El Colegio', tier: 4 },
      { nombre: 'Viotá', tier: 4 },
      { nombre: 'Nilo', tier: 4 },
      { nombre: 'Ricaurte', tier: 4 },
      { nombre: 'Agua de Dios', tier: 4 },
      { nombre: 'Tocaima', tier: 3 },
      { nombre: 'Guaduas', tier: 3 },
      { nombre: 'Villeta', tier: 3 },
      { nombre: 'Ubaté', tier: 3 },
      { nombre: 'Chocontá', tier: 3 },
      { nombre: 'Villapinzón', tier: 3 },
      { nombre: 'Suesca', tier: 3 },
      { nombre: 'Sesquilé', tier: 4 },
      { nombre: 'Nemocón', tier: 3 },
      { nombre: 'Cogua', tier: 3 },
      { nombre: 'Gachancipá', tier: 3 },
      { nombre: 'Guatavita', tier: 4 },
      { nombre: 'Guasca', tier: 4 },
      { nombre: 'Pacho', tier: 4 },
      { nombre: 'San Cayetano', tier: 4 },
      { nombre: 'Vergara', tier: 4 },
      { nombre: 'La Peña', tier: 4 },
      { nombre: 'Nimaima', tier: 4 },
      { nombre: 'Nocaima', tier: 4 },
      { nombre: 'Quebradanegra', tier: 4 },
      { nombre: 'Utica', tier: 4 },
      { nombre: 'Caparrapí', tier: 4 },
      { nombre: 'Puerto Salgar', tier: 4 },
      { nombre: 'Yacopí', tier: 4 },
      { nombre: 'Topaipí', tier: 4 },
    ],
  },
  {
    codigo: '27',
    nombre: 'Chocó',
    municipios: [
      { nombre: 'Quibdó', tier: 2 },
      { nombre: 'Istmina', tier: 3 },
      { nombre: 'Tadó', tier: 3 },
      { nombre: 'Riosucio', tier: 4 },
      { nombre: 'Condoto', tier: 4 },
      { nombre: 'Cértegui', tier: 4 },
      { nombre: 'El Carmen de Atrato', tier: 4 },
      { nombre: 'Lloró', tier: 4 },
      { nombre: 'Bagadó', tier: 4 },
      { nombre: 'Acandí', tier: 4 },
      { nombre: 'Bahía Solano', tier: 4 },
      { nombre: 'Nuquí', tier: 4 },
      { nombre: 'Juradó', tier: 4 },
    ],
  },
  {
    codigo: '41',
    nombre: 'Huila',
    municipios: [
      { nombre: 'Neiva', tier: 1 },
      { nombre: 'Pitalito', tier: 2 },
      { nombre: 'Garzón', tier: 2 },
      { nombre: 'La Plata', tier: 2 },
      { nombre: 'Campoalegre', tier: 3 },
      { nombre: 'Villavieja', tier: 3 },
      { nombre: 'Palermo', tier: 3 },
      { nombre: 'Rivera', tier: 3 },
      { nombre: 'Tello', tier: 3 },
      { nombre: 'Baraya', tier: 3 },
      { nombre: 'Aipe', tier: 3 },
      { nombre: 'Algeciras', tier: 4 },
      { nombre: 'Hobo', tier: 4 },
      { nombre: 'Yaguará', tier: 4 },
      { nombre: 'Tesalia', tier: 4 },
      { nombre: 'Paicol', tier: 4 },
      { nombre: 'Nátaga', tier: 4 },
      { nombre: 'Íquira', tier: 4 },
      { nombre: 'Teruel', tier: 4 },
      { nombre: 'Santa María', tier: 4 },
      { nombre: 'Suaza', tier: 4 },
      { nombre: 'Timaná', tier: 3 },
      { nombre: 'Altamira', tier: 4 },
      { nombre: 'Tarqui', tier: 4 },
      { nombre: 'Pital', tier: 4 },
      { nombre: 'Agrado', tier: 4 },
      { nombre: 'Saladoblanco', tier: 4 },
      { nombre: 'Oporapa', tier: 4 },
      { nombre: 'Elías', tier: 4 },
      { nombre: 'Isnos', tier: 4 },
      { nombre: 'San Agustín', tier: 3 },
      { nombre: 'Palestina', tier: 4 },
      { nombre: 'Acevedo', tier: 4 },
      { nombre: 'Gigante', tier: 4 },
      { nombre: 'Guadalupe', tier: 4 },
      { nombre: 'La Argentina', tier: 4 },
    ],
  },
  {
    codigo: '44',
    nombre: 'La Guajira',
    municipios: [
      { nombre: 'Riohacha', tier: 2 },
      { nombre: 'Maicao', tier: 2 },
      { nombre: 'Uribia', tier: 3 },
      { nombre: 'Manaure', tier: 3 },
      { nombre: 'San Juan del Cesar', tier: 3 },
      { nombre: 'Fonseca', tier: 3 },
      { nombre: 'Barrancas', tier: 3 },
      { nombre: 'Villanueva', tier: 3 },
      { nombre: 'Albania', tier: 4 },
      { nombre: 'Dibulla', tier: 4 },
      { nombre: 'Distracción', tier: 4 },
      { nombre: 'El Molino', tier: 4 },
      { nombre: 'Hatonuevo', tier: 4 },
      { nombre: 'La Jagua del Pilar', tier: 4 },
      { nombre: 'Urumita', tier: 4 },
    ],
  },
  {
    codigo: '47',
    nombre: 'Magdalena',
    municipios: [
      { nombre: 'Santa Marta', tier: 1 },
      { nombre: 'Ciénaga', tier: 2 },
      { nombre: 'Fundación', tier: 2 },
      { nombre: 'Zona Bananera', tier: 3 },
      { nombre: 'Aracataca', tier: 3 },
      { nombre: 'El Banco', tier: 3 },
      { nombre: 'Plato', tier: 3 },
      { nombre: 'Pivijay', tier: 3 },
      { nombre: 'Guamal', tier: 3 },
      { nombre: 'Chibolo', tier: 4 },
      { nombre: 'Concordia', tier: 4 },
      { nombre: 'El Piñón', tier: 4 },
      { nombre: 'El Retén', tier: 4 },
      { nombre: 'Nueva Granada', tier: 4 },
      { nombre: 'Pedraza', tier: 4 },
      { nombre: 'Pueblo Viejo', tier: 4 },
      { nombre: 'Remolino', tier: 4 },
      { nombre: 'Sabanas de San Ángel', tier: 4 },
      { nombre: 'Salamina', tier: 4 },
      { nombre: 'San Zenón', tier: 4 },
      { nombre: 'Santa Ana', tier: 4 },
      { nombre: 'Santa Bárbara de Pinto', tier: 4 },
      { nombre: 'Sitionuevo', tier: 4 },
      { nombre: 'Tenerife', tier: 4 },
      { nombre: 'Zapayán', tier: 4 },
      { nombre: 'Algarrobo', tier: 4 },
      { nombre: 'Ariguaní', tier: 4 },
      { nombre: 'Cerro de San Antonio', tier: 4 },
    ],
  },
  {
    codigo: '50',
    nombre: 'Meta',
    municipios: [
      { nombre: 'Villavicencio', tier: 1 },
      { nombre: 'Acacías', tier: 2 },
      { nombre: 'Granada', tier: 2 },
      { nombre: 'Puerto López', tier: 3 },
      { nombre: 'Cumaral', tier: 3 },
      { nombre: 'Restrepo', tier: 3 },
      { nombre: 'San Martín', tier: 3 },
      { nombre: 'Guamal', tier: 3 },
      { nombre: 'Castilla la Nueva', tier: 3 },
      { nombre: 'San Carlos de Guaroa', tier: 4 },
      { nombre: 'Puerto Gaitán', tier: 4 },
      { nombre: 'Puerto Concordia', tier: 4 },
      { nombre: 'Puerto Rico', tier: 4 },
      { nombre: 'Fuente de Oro', tier: 4 },
      { nombre: 'Barranca de Upía', tier: 4 },
      { nombre: 'Cabuyaro', tier: 4 },
      { nombre: 'Cubarral', tier: 4 },
      { nombre: 'El Calvario', tier: 4 },
      { nombre: 'El Castillo', tier: 4 },
      { nombre: 'El Dorado', tier: 4 },
      { nombre: 'La Macarena', tier: 4 },
      { nombre: 'Lejanías', tier: 4 },
      { nombre: 'Mapiripán', tier: 4 },
      { nombre: 'Mesetas', tier: 4 },
      { nombre: 'Puerto Lleras', tier: 4 },
      { nombre: 'San Juan de Arama', tier: 4 },
      { nombre: 'San Juanito', tier: 4 },
      { nombre: 'Uribe', tier: 4 },
      { nombre: 'Vistahermosa', tier: 4 },
    ],
  },
  {
    codigo: '52',
    nombre: 'Nariño',
    municipios: [
      { nombre: 'Pasto', tier: 1 },
      { nombre: 'Ipiales', tier: 2 },
      { nombre: 'Tumaco', tier: 2 },
      { nombre: 'Túquerres', tier: 2 },
      { nombre: 'La Unión', tier: 3 },
      { nombre: 'Sandoná', tier: 3 },
      { nombre: 'Consacá', tier: 3 },
      { nombre: 'Chachagüí', tier: 3 },
      { nombre: 'Buesaco', tier: 3 },
      { nombre: 'Tangua', tier: 3 },
      { nombre: 'Yacuanquer', tier: 3 },
      { nombre: 'Guaitarilla', tier: 3 },
      { nombre: 'Ancuya', tier: 4 },
      { nombre: 'Linares', tier: 4 },
      { nombre: 'Samaniego', tier: 4 },
      { nombre: 'Sotomayor', tier: 4 },
      { nombre: 'Providencia', tier: 4 },
      { nombre: 'Ricaurte', tier: 4 },
      { nombre: 'Mallama', tier: 4 },
      { nombre: 'Cumbal', tier: 4 },
      { nombre: 'Aldana', tier: 4 },
      { nombre: 'Guachucal', tier: 4 },
      { nombre: 'Córdoba', tier: 4 },
      { nombre: 'Puerres', tier: 4 },
      { nombre: 'Funes', tier: 4 },
      { nombre: 'El Contadero', tier: 4 },
      { nombre: 'Pupiales', tier: 4 },
      { nombre: 'Imués', tier: 4 },
      { nombre: 'Ospina', tier: 4 },
      { nombre: 'Sapuyes', tier: 4 },
    ],
  },
  {
    codigo: '54',
    nombre: 'Norte de Santander',
    municipios: [
      { nombre: 'Cúcuta', tier: 1 },
      { nombre: 'Villa del Rosario', tier: 1 },
      { nombre: 'Los Patios', tier: 1 },
      { nombre: 'Ocaña', tier: 2 },
      { nombre: 'Pamplona', tier: 2 },
      { nombre: 'Tibú', tier: 2 },
      { nombre: 'El Zulia', tier: 2 },
      { nombre: 'San Cayetano', tier: 3 },
      { nombre: 'Puerto Santander', tier: 3 },
      { nombre: 'Sardinata', tier: 3 },
      { nombre: 'El Tarra', tier: 3 },
      { nombre: 'Convención', tier: 3 },
      { nombre: 'La Playa de Belén', tier: 3 },
      { nombre: 'Ábrego', tier: 4 },
      { nombre: 'Hacarí', tier: 4 },
      { nombre: 'San Calixto', tier: 4 },
      { nombre: 'Teorama', tier: 4 },
      { nombre: 'El Carmen', tier: 4 },
      { nombre: 'González', tier: 4 },
      { nombre: 'Río de Oro', tier: 4 },
      { nombre: 'Chitagá', tier: 4 },
      { nombre: 'Pamplonita', tier: 4 },
      { nombre: 'Mutiscua', tier: 4 },
      { nombre: 'Silos', tier: 4 },
      { nombre: 'Cácota', tier: 4 },
      { nombre: 'Labateca', tier: 4 },
      { nombre: 'Toledo', tier: 4 },
      { nombre: 'Herrán', tier: 4 },
    ],
  },
  {
    codigo: '63',
    nombre: 'Quindío',
    municipios: [
      { nombre: 'Armenia', tier: 1 },
      { nombre: 'Calarcá', tier: 2 },
      { nombre: 'Montenegro', tier: 2 },
      { nombre: 'Salento', tier: 3 },
      { nombre: 'Quimbaya', tier: 3 },
      { nombre: 'La Tebaida', tier: 3 },
      { nombre: 'Circasia', tier: 3 },
      { nombre: 'Filandia', tier: 3 },
      { nombre: 'Córdoba', tier: 4 },
      { nombre: 'Pijao', tier: 4 },
      { nombre: 'Génova', tier: 4 },
      { nombre: 'Buenavista', tier: 4 },
    ],
  },
  {
    codigo: '66',
    nombre: 'Risaralda',
    municipios: [
      { nombre: 'Pereira', tier: 1 },
      { nombre: 'Dosquebradas', tier: 1 },
      { nombre: 'Santa Rosa de Cabal', tier: 2 },
      { nombre: 'La Virginia', tier: 2 },
      { nombre: 'Marsella', tier: 3 },
      { nombre: 'Belén de Umbría', tier: 3 },
      { nombre: 'Apía', tier: 3 },
      { nombre: 'Santuario', tier: 3 },
      { nombre: 'Quinchía', tier: 4 },
      { nombre: 'Guática', tier: 4 },
      { nombre: 'Mistrató', tier: 4 },
      { nombre: 'Pueblo Rico', tier: 4 },
      { nombre: 'La Celia', tier: 4 },
      { nombre: 'Balboa', tier: 4 },
    ],
  },
  {
    codigo: '68',
    nombre: 'Santander',
    municipios: [
      { nombre: 'Bucaramanga', tier: 1 },
      { nombre: 'Floridablanca', tier: 1 },
      { nombre: 'Girón', tier: 1 },
      { nombre: 'Piedecuesta', tier: 1 },
      { nombre: 'Barrancabermeja', tier: 1 },
      { nombre: 'San Gil', tier: 2 },
      { nombre: 'Socorro', tier: 2 },
      { nombre: 'Vélez', tier: 2 },
      { nombre: 'Málaga', tier: 2 },
      { nombre: 'Zapatoca', tier: 3 },
      { nombre: 'Lebrija', tier: 3 },
      { nombre: 'Rionegro', tier: 3 },
      { nombre: 'Puerto Wilches', tier: 3 },
      { nombre: 'Sabana de Torres', tier: 3 },
      { nombre: 'Cimitarra', tier: 3 },
      { nombre: 'Landázuri', tier: 4 },
      { nombre: 'Barichara', tier: 3 },
      { nombre: 'Curití', tier: 3 },
      { nombre: 'Aratoca', tier: 4 },
      { nombre: 'Los Santos', tier: 4 },
      { nombre: 'Jordán', tier: 4 },
      { nombre: 'Villanueva', tier: 4 },
      { nombre: 'San Vicente de Chucurí', tier: 4 },
      { nombre: 'El Carmen de Chucurí', tier: 4 },
      { nombre: 'Puerto Parra', tier: 4 },
      { nombre: 'Puente Nacional', tier: 3 },
      { nombre: 'Barbosa', tier: 3 },
      { nombre: 'Oiba', tier: 4 },
      { nombre: 'Contratación', tier: 4 },
      { nombre: 'Guadalupe', tier: 4 },
      { nombre: 'Guapotá', tier: 4 },
      { nombre: 'Palmar', tier: 4 },
      { nombre: 'Simacota', tier: 4 },
      { nombre: 'Galán', tier: 4 },
    ],
  },
  {
    codigo: '70',
    nombre: 'Sucre',
    municipios: [
      { nombre: 'Sincelejo', tier: 1 },
      { nombre: 'Corozal', tier: 2 },
      { nombre: 'San Marcos', tier: 2 },
      { nombre: 'Sampués', tier: 2 },
      { nombre: 'Sahagún', tier: 2 },
      { nombre: 'Tolú', tier: 2 },
      { nombre: 'Coveñas', tier: 2 },
      { nombre: 'San Onofre', tier: 3 },
      { nombre: 'Tolú Viejo', tier: 3 },
      { nombre: 'Los Palmitos', tier: 3 },
      { nombre: 'Morroa', tier: 3 },
      { nombre: 'Ovejas', tier: 3 },
      { nombre: 'San Juan de Betulia', tier: 3 },
      { nombre: 'San Pedro', tier: 3 },
      { nombre: 'Sincé', tier: 3 },
      { nombre: 'Buenavista', tier: 4 },
      { nombre: 'Caimito', tier: 4 },
      { nombre: 'Colosó', tier: 4 },
      { nombre: 'Chalán', tier: 4 },
      { nombre: 'Galeras', tier: 4 },
      { nombre: 'Guaranda', tier: 4 },
      { nombre: 'La Unión', tier: 4 },
      { nombre: 'Majagual', tier: 4 },
      { nombre: 'Palmito', tier: 4 },
      { nombre: 'San Benito Abad', tier: 4 },
      { nombre: 'Sucre', tier: 4 },
    ],
  },
  {
    codigo: '73',
    nombre: 'Tolima',
    municipios: [
      { nombre: 'Ibagué', tier: 1 },
      { nombre: 'Espinal', tier: 2 },
      { nombre: 'Melgar', tier: 2 },
      { nombre: 'Líbano', tier: 2 },
      { nombre: 'Chaparral', tier: 2 },
      { nombre: 'Mariquita', tier: 2 },
      { nombre: 'Honda', tier: 2 },
      { nombre: 'Guamo', tier: 2 },
      { nombre: 'Purificación', tier: 3 },
      { nombre: 'Flandes', tier: 3 },
      { nombre: 'Coello', tier: 3 },
      { nombre: 'Cajamarca', tier: 3 },
      { nombre: 'Rovira', tier: 3 },
      { nombre: 'San Luis', tier: 3 },
      { nombre: 'Valle de San Juan', tier: 3 },
      { nombre: 'Saldaña', tier: 3 },
      { nombre: 'Natagaima', tier: 3 },
      { nombre: 'Alpujarra', tier: 4 },
      { nombre: 'Alvarado', tier: 4 },
      { nombre: 'Ambalema', tier: 4 },
      { nombre: 'Anzoátegui', tier: 4 },
      { nombre: 'Armero', tier: 4 },
      { nombre: 'Ataco', tier: 4 },
      { nombre: 'Carmen de Apicalá', tier: 4 },
      { nombre: 'Casabianca', tier: 4 },
      { nombre: 'Cunday', tier: 4 },
      { nombre: 'Dolores', tier: 4 },
      { nombre: 'Falan', tier: 4 },
      { nombre: 'Fresno', tier: 4 },
      { nombre: 'Herveo', tier: 4 },
      { nombre: 'Icononzo', tier: 4 },
      { nombre: 'Lérida', tier: 4 },
      { nombre: 'Murillo', tier: 4 },
      { nombre: 'Ortega', tier: 4 },
      { nombre: 'Palocabildo', tier: 4 },
      { nombre: 'Piedras', tier: 4 },
      { nombre: 'Planadas', tier: 4 },
      { nombre: 'Prado', tier: 4 },
      { nombre: 'Rioblanco', tier: 4 },
      { nombre: 'Roncesvalles', tier: 4 },
      { nombre: 'San Antonio', tier: 4 },
      { nombre: 'Santa Isabel', tier: 4 },
      { nombre: 'Suárez', tier: 4 },
      { nombre: 'Villarrica', tier: 4 },
    ],
  },
  {
    codigo: '76',
    nombre: 'Valle del Cauca',
    municipios: [
      { nombre: 'Cali', tier: 1 },
      { nombre: 'Palmira', tier: 1 },
      { nombre: 'Yumbo', tier: 1 },
      { nombre: 'Buenaventura', tier: 1 },
      { nombre: 'Tuluá', tier: 2 },
      { nombre: 'Cartago', tier: 2 },
      { nombre: 'Buga', tier: 2 },
      { nombre: 'Jamundí', tier: 2 },
      { nombre: 'Candelaria', tier: 2 },
      { nombre: 'Florida', tier: 2 },
      { nombre: 'Pradera', tier: 2 },
      { nombre: 'Sevilla', tier: 3 },
      { nombre: 'Zarzal', tier: 3 },
      { nombre: 'Roldanillo', tier: 3 },
      { nombre: 'La Unión', tier: 3 },
      { nombre: 'La Victoria', tier: 3 },
      { nombre: 'Obando', tier: 3 },
      { nombre: 'Andalucía', tier: 3 },
      { nombre: 'Toro', tier: 3 },
      { nombre: 'Versalles', tier: 3 },
      { nombre: 'El Dovio', tier: 4 },
      { nombre: 'Alcalá', tier: 4 },
      { nombre: 'Ansermanuevo', tier: 4 },
      { nombre: 'Argelia', tier: 4 },
      { nombre: 'Bolívar', tier: 4 },
      { nombre: 'Bugalagrande', tier: 3 },
      { nombre: 'Caicedonia', tier: 3 },
      { nombre: 'Calima', tier: 4 },
      { nombre: 'Dagua', tier: 4 },
      { nombre: 'El Águila', tier: 4 },
      { nombre: 'El Cairo', tier: 4 },
      { nombre: 'El Cerrito', tier: 3 },
      { nombre: 'Ginebra', tier: 3 },
      { nombre: 'Guacarí', tier: 3 },
      { nombre: 'La Cumbre', tier: 4 },
      { nombre: 'Restrepo', tier: 4 },
      { nombre: 'Riofrío', tier: 4 },
      { nombre: 'San Pedro', tier: 4 },
      { nombre: 'Trujillo', tier: 4 },
      { nombre: 'Ulloa', tier: 4 },
      { nombre: 'Vijes', tier: 4 },
      { nombre: 'Yotoco', tier: 4 },
    ],
  },
  {
    codigo: '81',
    nombre: 'Arauca',
    municipios: [
      { nombre: 'Arauca', tier: 2 },
      { nombre: 'Saravena', tier: 2 },
      { nombre: 'Tame', tier: 3 },
      { nombre: 'Arauquita', tier: 3 },
      { nombre: 'Fortul', tier: 3 },
      { nombre: 'Puerto Rondón', tier: 4 },
      { nombre: 'Cravo Norte', tier: 4 },
    ],
  },
  {
    codigo: '85',
    nombre: 'Casanare',
    municipios: [
      { nombre: 'Yopal', tier: 2 },
      { nombre: 'Aguazul', tier: 2 },
      { nombre: 'Villanueva', tier: 3 },
      { nombre: 'Tauramena', tier: 3 },
      { nombre: 'Monterrey', tier: 3 },
      { nombre: 'Paz de Ariporo', tier: 3 },
      { nombre: 'Hato Corozal', tier: 4 },
      { nombre: 'Pore', tier: 4 },
      { nombre: 'San Luis de Palenque', tier: 4 },
      { nombre: 'Trinidad', tier: 4 },
      { nombre: 'Maní', tier: 4 },
      { nombre: 'Orocué', tier: 4 },
      { nombre: 'Chámeza', tier: 4 },
      { nombre: 'Recetor', tier: 4 },
      { nombre: 'Sácama', tier: 4 },
      { nombre: 'Támara', tier: 4 },
      { nombre: 'La Salina', tier: 4 },
      { nombre: 'Nunchía', tier: 4 },
      { nombre: 'Sabanalarga', tier: 4 },
    ],
  },
  {
    codigo: '86',
    nombre: 'Putumayo',
    municipios: [
      { nombre: 'Mocoa', tier: 2 },
      { nombre: 'Puerto Asís', tier: 2 },
      { nombre: 'Orito', tier: 3 },
      { nombre: 'Valle del Guamuez', tier: 3 },
      { nombre: 'Villagarzón', tier: 3 },
      { nombre: 'San Miguel', tier: 3 },
      { nombre: 'Puerto Caicedo', tier: 4 },
      { nombre: 'Puerto Guzmán', tier: 4 },
      { nombre: 'Puerto Leguízamo', tier: 4 },
      { nombre: 'Sibundoy', tier: 4 },
      { nombre: 'San Francisco', tier: 4 },
      { nombre: 'Santiago', tier: 4 },
      { nombre: 'Colón', tier: 4 },
    ],
  },
  {
    codigo: '88',
    nombre: 'Archipiélago de San Andrés',
    municipios: [
      { nombre: 'San Andrés', tier: 3 },
      { nombre: 'Providencia', tier: 3 },
    ],
  },
  {
    codigo: '91',
    nombre: 'Amazonas',
    municipios: [
      { nombre: 'Leticia', tier: 3 },
      { nombre: 'Puerto Nariño', tier: 4 },
    ],
  },
  {
    codigo: '94',
    nombre: 'Guainía',
    municipios: [
      { nombre: 'Inírida', tier: 3 },
    ],
  },
  {
    codigo: '95',
    nombre: 'Guaviare',
    municipios: [
      { nombre: 'San José del Guaviare', tier: 3 },
      { nombre: 'Calamar', tier: 4 },
      { nombre: 'El Retorno', tier: 4 },
      { nombre: 'Miraflores', tier: 4 },
    ],
  },
  {
    codigo: '97',
    nombre: 'Vaupés',
    municipios: [
      { nombre: 'Mitú', tier: 3 },
      { nombre: 'Carurú', tier: 4 },
    ],
  },
  {
    codigo: '99',
    nombre: 'Vichada',
    municipios: [
      { nombre: 'Puerto Carreño', tier: 4 },
      { nombre: 'La Primavera', tier: 4 },
      { nombre: 'Santa Rosalía', tier: 4 },
      { nombre: 'Cumaribo', tier: 4 },
    ],
  },
];

/**
 * Obtiene los municipios de un departamento
 */
export function getCiudadesPorDepartamento(nombreDepartamento: string): Municipio[] {
  const depto = DEPARTAMENTOS_COLOMBIA.find((d) => d.nombre === nombreDepartamento);
  return depto ? depto.municipios : [];
}

/**
 * Obtiene el tier de un municipio específico
 */
export function getTierMunicipio(departamento: string, municipio: string): ShippingTier {
  const depto = DEPARTAMENTOS_COLOMBIA.find((d) => d.nombre === departamento);
  if (!depto) return 4;
  const mun = depto.municipios.find((m) => m.nombre === municipio);
  return mun ? mun.tier : 4;
}